"""
Main entry point for the multi-agent system.
Provides Squad-like terminal output with progress tracking, agent status,
and formatted execution summaries.
"""

import sys
import json
import argparse
from pathlib import Path
from datetime import datetime
from src.graph import invoke_graph, stream_graph
from src.config import AGENTS, MODELS, get_routing_agent
from src.squad_runtime import format_plan_for_display, init_squad


# ============================================================================
# Terminal Formatting Helpers
# ============================================================================

def _format_header(title: str, width: int = 70):
    """Format and print a main header."""
    print(f"\n{'='*width}")
    print(f"{title.center(width)}")
    print(f"{'='*width}\n")


def _format_section(title: str, symbol: str = ""):
    """Format and print a section divider."""
    if symbol:
        print(f"\n[{symbol}] {title}")
    else:
        print(f"\n[{title}]")
    print(f"{'-'*60}")


def _format_status(text: str, status_type: str = "info"):
    """Print status with symbol."""
    symbols = {
        "info": "[*]",
        "success": "[OK]",
        "error": "[!]",
        "working": "[>]",
        "plan": "[P]",
        "code": "[C]",
        "util": "[U]",
    }
    symbol = symbols.get(status_type, "[*]")
    print(f"{symbol} {text}")


def _format_box(content: str, title: str = "", padding: int = 2):
    """Print content in a formatted box."""
    lines = content.strip().split('\n')
    max_width = max([len(line) for line in lines] + [40])
    
    if title:
        print(f"\n[{title}]")
    
    for line in lines:
        print(f"{'  ' * padding}{line}")
    print()


def _format_agent_card(agent_name: str, model_name: str, task: str):
    """Print a formatted agent assignment card."""
    print(f"\n{'='*60}")
    print(f"  AGENT: {agent_name.upper():<20} MODEL: {model_name}")
    print(f"{'='*60}")
    print(f"  Task: {task[:50]}{'...' if len(task) > 50 else ''}")
    print(f"{'='*60}\n")


def _format_execution_summary(final_state: dict, log_file: str = ""):
    """Print a formatted execution summary."""
    print(f"\n{'='*60}")
    print(f"{'EXECUTION SUMMARY'.center(60)}")
    print(f"{'='*60}\n")
    
    status = final_state.get("status", "unknown")
    task = final_state.get("user_task", "")
    
    _format_status(f"Status: {status}", "success")
    _format_status(f"Task: {task[:60]}{'...' if len(task) > 60 else ''}")
    
    if final_state.get("plan"):
        _format_status("Plan generated by PLANNER", "plan")
    
    if final_state.get("implementation"):
        _format_status("Code generated by CODER", "code")
    
    if final_state.get("utility_output"):
        _format_status("Boilerplate generated by UTILITY", "util")

    files_written = final_state.get("files_written") or []
    if files_written:
        _format_status(f"Files written: {len(files_written)}", "success")

    if final_state.get("file_write_error"):
        _format_status(f"File write error: {final_state['file_write_error']}", "error")
    
    if log_file:
        _format_status(f"Log saved: {log_file}", "success")
    
    print()


def _get_latest_log():
    """Get the most recent log file from .squad/log/"""
    log_dir = Path(".squad/log")
    if not log_dir.exists():
        return None

    markdown_files = [
        path for path in log_dir.glob("*.md")
        if not path.name.startswith("agent_")
    ]
    if markdown_files:
        return str(max(markdown_files, key=lambda path: path.stat().st_mtime))

    json_files = sorted(log_dir.glob("session_*.json"), reverse=True)
    if json_files:
        return str(json_files[0])
    return None


def _print_log_summary(log_file: str):
    """Print a summary of the log file."""
    try:
        log_path = Path(log_file)
        if log_path.suffix.lower() == ".md":
            content = log_path.read_text(encoding="utf-8")
            _format_section("EXECUTION LOG DETAILS")
            preview_lines = []
            for line in content.splitlines():
                if line == "## Result":
                    preview_lines.append(line)
                    break
                if line.startswith("# ") or line.startswith("| **") or line.startswith("## "):
                    preview_lines.append(line)
                if len(preview_lines) >= 12:
                    break

            for line in preview_lines:
                print(line)
            print(f"\nFull log: {log_file}")
            return

        with open(log_file, 'r', encoding="utf-8") as f:
            log_data = json.load(f)
        
        _format_section("EXECUTION LOG DETAILS")
        
        print(f"Timestamp: {log_data.get('timestamp', 'unknown')}")
        print(f"Status: {log_data.get('status', 'unknown')}")
        print(f"Next Agent: {log_data.get('next_agent', 'none')}")
        
        # Show plan if exists
        if log_data.get('plan'):
            print(f"\n[PLAN OUTPUT] (first 300 chars)")
            print(f"{format_plan_for_display(log_data['plan'])[:300]}...")
        
        # Show implementation if exists
        if log_data.get('implementation'):
            print(f"\n[IMPLEMENTATION OUTPUT] (first 300 chars)")
            print(f"{log_data['implementation'][:300]}...")
        
        # Show utility if exists
        if log_data.get('utility_output'):
            print(f"\n[UTILITY OUTPUT] (first 300 chars)")
            print(f"{log_data['utility_output'][:300]}...")
        
        print(f"\nFull log: {log_file}")
    
    except Exception as e:
        print(f"Could not read log: {e}")


# ============================================================================
# System Information
# ============================================================================

def print_system_info():
    """Print system configuration with Squad-like formatting."""
    _format_header("MULTI-AGENT LOCAL SYSTEM")
    
    _format_section("AVAILABLE MODELS", "MODELS")
    for model_name, model_config in MODELS.items():
        print(f"\n  {model_name}")
        print(f"    - Role: {model_config.role.value}")
        print(f"    - Description: {model_config.description}")
        print(f"    - Settings: temp={model_config.temperature}, max_tokens={model_config.max_tokens}")
    
    _format_section("AVAILABLE AGENTS", "AGENTS")
    for agent_name, agent_config in AGENTS.items():
        print(f"\n  {agent_name}")
        print(f"    - Model: {agent_config.model.name}")
        print(f"    - Role: {agent_config.role}")
        print(f"    - {agent_config.description}")
    
    _format_section("ROUTING RULES", "ROUTING")
    print("\n  - PLANNER: Keywords 'plan', 'design', 'architecture', 'strategy'")
    print("    -> Complex tasks requiring decomposition")
    print("\n  - CODER: Keywords 'implement', 'refactor', 'debug', 'code', 'fix'")
    print("    -> Code generation and complex implementations")
    print("\n  - FAST_UTILITY: Keywords 'quick', 'simple', 'template', 'boilerplate'")
    print("    -> Quick edits and boilerplate generation")


# ============================================================================
# Example Tasks
# ============================================================================

def example_planning_task():
    """Example 1: Complex planning task."""
    task = """Design a Python FastAPI-based REST API for a todo application with:
- CRUD operations for todos
- User authentication with JWT
- SQLAlchemy ORM integration
- Environment variable configuration
- Error handling and validation

Break this down into clear implementation steps."""
    
    _format_header("EXAMPLE 1: COMPLEX PLANNING")
    _format_section("TASK DESCRIPTION")
    print(task)
    
    _format_section("EXECUTION", "RUNNING")
    print("Routing to PLANNER for task decomposition...\n")
    
    final_state = invoke_graph(task, verbose=False, save_logs=True)
    
    log_file = _get_latest_log()
    _format_execution_summary(final_state, log_file)
    
    if final_state.get("plan"):
        _format_section("PLANNER OUTPUT")
        print(format_plan_for_display(final_state["plan"])[:700])
    
    if log_file:
        _print_log_summary(log_file)


def example_coding_task():
    """Example 2: Direct coding task."""
    task = """Generate a Python function that:
1. Reads a JSON file
2. Filters items where count > 5
3. Sorts by date descending
4. Returns formatted results

Include proper error handling and type hints."""
    
    _format_header("EXAMPLE 2: CODE GENERATION")
    _format_section("TASK DESCRIPTION")
    print(task)
    
    _format_section("EXECUTION", "RUNNING")
    print("Routing to CODER for implementation...\n")
    
    final_state = invoke_graph(task, verbose=False, save_logs=True)
    
    log_file = _get_latest_log()
    _format_execution_summary(final_state, log_file)
    
    if final_state.get("implementation"):
        _format_section("CODER OUTPUT")
        print(final_state["implementation"][:700])
    
    if log_file:
        _print_log_summary(log_file)


def example_quick_task():
    """Example 3: Quick utility task."""
    task = """Generate a quick Python class template for a data model with:
- name (str)
- email (str)
- created_at (datetime)
- is_active (bool)

Make it compatible with Pydantic."""
    
    _format_header("EXAMPLE 3: QUICK BOILERPLATE")
    _format_section("TASK DESCRIPTION")
    print(task)
    
    _format_section("EXECUTION", "RUNNING")
    print("Routing to FAST_UTILITY for quick generation...\n")
    
    final_state = invoke_graph(task, verbose=False, save_logs=True)
    
    log_file = _get_latest_log()
    _format_execution_summary(final_state, log_file)
    
    if final_state.get("utility_output"):
        _format_section("UTILITY OUTPUT")
        print(final_state["utility_output"][:700])
    
    if log_file:
        _print_log_summary(log_file)


# ============================================================================
# Interactive Mode
# ============================================================================

def interactive_mode():
    """Interactive mode with Squad-like interface."""
    _format_section("INTERACTIVE MODE", "INTERACTIVE")
    print("Enter your task (or 'quit' to exit)\n")
    
    execution_count = 0
    
    while True:
        try:
            task = input(">>> ").strip()
            
            if task.lower() in ["quit", "exit", "q"]:
                _format_status("Goodbye!", "success")
                break
            
            if not task:
                print("Please enter a task.\n")
                continue
            
            execution_count += 1
            
            # Show routing info
            assigned_agent = get_routing_agent(task)
            agent_config = AGENTS.get(assigned_agent, AGENTS["planner"])
            model_name = agent_config.model.name
            
            _format_agent_card(assigned_agent, model_name, task)
            
            # Execute
            _format_status("Processing...", "working")
            final_state = invoke_graph(task, verbose=False, save_logs=True)
            
            # Show results
            log_file = _get_latest_log()
            _format_execution_summary(final_state, log_file)
            
            # Show output based on which agent was used
            if final_state.get("plan"):
                _format_box(format_plan_for_display(final_state["plan"])[:500], "PLAN OUTPUT")
            
            if final_state.get("implementation"):
                _format_box(final_state["implementation"][:500], "IMPLEMENTATION OUTPUT")
            
            if final_state.get("utility_output"):
                _format_box(final_state["utility_output"][:500], "UTILITY OUTPUT")

            if final_state.get("files_written"):
                _format_box("\n".join(final_state["files_written"]), "FILES WRITTEN")
            
            if log_file:
                print(f"[LOG] Full execution log: {log_file}\n")
        
        except KeyboardInterrupt:
            print("\n")
            _format_status("Interrupted by user", "error")
            break
        except Exception as e:
            _format_status(f"Error: {str(e)}", "error")
            print()


def run_custom_task(task: str):
    """Execute one user task from the CLI."""
    print_system_info()

    assigned_agent = get_routing_agent(task)
    agent_config = AGENTS.get(assigned_agent, AGENTS["planner"])
    model_name = agent_config.model.name

    _format_agent_card(assigned_agent, model_name, task)

    _format_status("Processing task...", "working")
    final_state = invoke_graph(task, verbose=False, save_logs=True)

    log_file = _get_latest_log()
    _format_execution_summary(final_state, log_file)

    if final_state.get("plan"):
        _format_box(format_plan_for_display(final_state["plan"])[:600], "PLAN OUTPUT")

    if final_state.get("implementation"):
        _format_box(final_state["implementation"][:600], "IMPLEMENTATION OUTPUT")

    if final_state.get("utility_output"):
        _format_box(final_state["utility_output"][:600], "UTILITY OUTPUT")

    if final_state.get("files_written"):
        _format_box("\n".join(final_state["files_written"]), "FILES WRITTEN")

    if log_file:
        _print_log_summary(log_file)


# ============================================================================
# Main Entry Point
# ============================================================================

def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Local multi-agent system with Ollama - Squad Edition"
    )
    parser.add_argument(
        "mode",
        nargs="?",
        choices=["init", "interactive", "example1", "example2", "example3", "info"],
        default="info",
        help="Execution mode"
    )
    parser.add_argument(
        "--task",
        type=str,
        help="Custom task to execute"
    )
    parser.add_argument(
        "--project",
        type=str,
        default=".",
        help="Project root for squad init and file writes"
    )
    
    args = parser.parse_args()
    
    try:
        if args.mode == "init":
            _format_header("INITIALIZING LOCAL SQUAD")
            created = init_squad(args.project)
            if created:
                _format_status("Created runtime files:", "success")
                for path in created:
                    print(f"  {path}")
            else:
                _format_status("Local squad runtime already initialized", "success")
            print("\nRun tasks with: python -m src.main --task \"your task\"\n")

        elif args.task:
            run_custom_task(args.task)

        elif args.mode == "info":
            print_system_info()
            _format_section("USAGE EXAMPLES")
            print("\n  python -m src.main init                # Initialize .squad runtime")
            print("  python -m src.main interactive         # Interactive mode")
            print("  python -m src.main example1            # Planning example")
            print("  python -m src.main example2            # Coding example")
            print("  python -m src.main example3            # Quick boilerplate example")
            print("  python -m src.main --task 'your task'  # Custom task\n")
        
        elif args.mode == "interactive":
            print_system_info()
            interactive_mode()
        
        elif args.mode == "example1":
            example_planning_task()
        
        elif args.mode == "example2":
            example_coding_task()
        
        elif args.mode == "example3":
            example_quick_task()
    
    except KeyboardInterrupt:
        print("\n")
        _format_status("Interrupted by user", "error")
        sys.exit(1)
    except Exception as e:
        print(f"\n")
        _format_status(f"Error: {str(e)}", "error")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
